"""
About:
------
The semantic_relatedness command line interface (CLI) is designed to computes the degree of association between two sentences. As follows:

Usage:
------
Below is the usage information that can be generated by running semantic_relatedness --help.

.. code-block:: none

    semantic_relatedness –-sentence1 "your Arabic sentence here" --sentence2 "your Arabic sentence here"

Options:
--------
.. code-block:: none

    --sentence1 INPUT_TEXT
          The Arabic sentence to find the semantic relatedness between it and the second sentence.
    --sentence2 INPUT_TEXT
          The Arabic sentence to find the semantic relatedness between it and the first sentence.

Examples:
---------
.. code-block:: none

    semantic_relatedness --sentence1 "Your text here" --sentence2 "Your text here"
"""

import argparse
from sinatools.semantic_relatedness.compute_relatedness import get_similarity_score

def main():
    parser = argparse.ArgumentParser(description='Computes the degree of association between two sentences across various dimensions, meaning, underlying concepts, domain-specificity, topic overlap, viewpoint alignment.')
      
    parser.add_argument('--sentence1', type=str, help='The first sentence to be compute similarity based on')
    parser.add_argument('--sentence2', type=str, help='The second sentence to be compute similarity based on')
    

    args = parser.parse_args()

    if args.sentence1 is None and args.sentence2 is None:
        print("Error: Either --sentence1 or --sentence2 argument must be provided.")
        return

    score = get_similarity_score(args.sentence1, args.sentence2)

    print(score)

if __name__ == '__main__':
    main()
