"""
Word-sense disambiguation command line

About:
------
The WSD command line interface (CLI) is a tool designed to utilize the wsd function for processing Arabic sentences. This CLI allows users to input an Arabic sentence and receive a structured response that includes the processing result of the SALMA function.

Usage:
------
Below is the usage information that can be generated by running the command with the --help option.

.. code-block:: none

    wsd --text=TEXT
    wsd --file=INPUT_FILE

Options:
--------
.. code-block:: none

  --text
        The Arabic sentence to be processed by the WSD function.
  --file 
        The text file to be processed by the WSD function.

Examples:
---------
.. code-block:: none

    wsd --text "your Arabic sentence here"
    wsd --file "path/to/your/file.txt"

"""

import argparse
import json
from sinatools.wsd.disambiguator import disambiguate
from sinatools.utils.readfile import read_file

def main():
    parser = argparse.ArgumentParser(description='Arabic text stripping tool using SinaTools')
    
    parser.add_argument('--text', type=str, help='Input sentence to process')
    parser.add_argument('--file', type=str, help='File containing the Arabic sentence to process')

    args = parser.parse_args()

    if args.text is None and args.file is None:
        print("Either --text or --file argument must be provided.")
        return
    
    text_content = args.text if args.text else " ".join(read_file(args.file))
    result = disambiguate(text_content)
    print(json.dumps(result, ensure_ascii=False, indent=4))

if __name__ == "__main__":
    main()

#wsd --text "your Arabic sentence here"
#wsd --file "path/to/your/file.txt"