"""
About:
------
The WSD command line interface (CLI) is designed to utilize the word sense disambiguation for Arabic sentences. This CLI allows users to input an Arabic sentence and receive concepts and lemma for each token within the sentence. As follows:

Usage:
------
Below is the usage information that can be generated by running wsd --help.

.. code-block:: none

    wsd –-text "your Arabic sentence here"
    wsd –-file path/to/txt/file

Options:
--------
.. code-block:: none

  --text INPUT_TEXT
        The text that needs to be analyzed for Named Entity Recognition.
  --file txt_file_path
        Directory containing the text files to be analyzed for Named Entity Recognition

Examples:
---------
.. code-block:: none

    wsd --text "Your text here"
    wsd --file "path/to/your/txt/file"

"""

import argparse
import json
from sinatools.wsd.disambiguator import disambiguate
from sinatools.utils.readfile import read_file

def main():
    parser = argparse.ArgumentParser(description='Arabic text stripping tool using SinaTools')
    
    parser.add_argument('--text', type=str, help='Input sentence to process')
    parser.add_argument('--file', type=str, help='File containing the Arabic sentence to process')

    args = parser.parse_args()

    if args.text is None and args.file is None:
        print("Either --text or --file argument must be provided.")
        return
    
    text_content = args.text if args.text else " ".join(read_file(args.file))
    result = disambiguate(text_content)
    print(json.dumps(result, ensure_ascii=False, indent=4))

if __name__ == "__main__":
    main()

#wsd --text "your Arabic sentence here"
#wsd --file "path/to/your/file.txt"