"""
About:
------
The evaluate_synonyms command line interface (CLI) is designed to take a set of synonyms and a level number, then evaluate how much these synonyms are realy a synonyms in this set. As follows:

Usage:
------
Below is the usage information that can be generated by running synonyms --help.

.. code-block:: none

    evaluate_synonyms –-synset "your synset here" --level level_number

Options:
--------
.. code-block:: none

    --synset INPUT_TEXT
            A set of synonyms to be evaluated (string of synonyms seperated by |)
    --level Integer
            The level number indicating the depth of synonym extension. Which could be 2 or 3

Examples:
---------
.. code-block:: none

    evaluate_synonyms --synset "ممر | طريق" --level 2
"""

import argparse
from sinatools.synonyms.synonyms_generator import evaluate_synonyms

def main():
    parser = argparse.ArgumentParser(description='Morphological Analysis using SinaTools')
      
    parser.add_argument('--synset', type=str, help='Set of synonyms seperated by |')
    parser.add_argument('--level', type=int, help='The depth of edges the algorithm needs to reach')

    args = parser.parse_args()

    if args.synset is None and args.level is None:
        print("Error: Either --synset or --level argument must be provided.")
        return

    results = evaluate_synonyms(args.synset, args.level)

    print(results)

if __name__ == '__main__':
    main()
