"""
About:
------
The extend_synonyms command line interface (CLI) is designed to receives a set of synonyms and a level number, then extends this set of synonyms with additional synonyms. Each synonym is assigned a fuzzy value based on the specified level. As follows:

Usage:
------
Below is the usage information that can be generated by running synonyms --help.

.. code-block:: none

    extend_synonyms –-synset "your synset here" --level level_number

Options:
--------
.. code-block:: none

    --synset INPUT_TEXT
          A set of initial synonyms to be extended (string of synonyms seperated by |)
    --level Integer
          The level number indicating the depth of synonym extension. Which could be 2 or 3

Examples:
---------
.. code-block:: none

    extend_synonyms --synset "ممر | طريق" --level 2
"""

import argparse
from sinatools.synonyms.synonyms_generator import extend_synonyms

def main():
    parser = argparse.ArgumentParser(description='Morphological Analysis using SinaTools')
      
    parser.add_argument('--synset', type=str, help='Set of synonyms seperated by |')
    parser.add_argument('--level', type=int, help='The depth of edges the algorithm needs to reach')

    args = parser.parse_args()

    if args.synset is None and args.level is None:
        print("Error: Either --synset or --level argument must be provided.")
        return

    results = extend_synonyms(args.synset, args.level)

    print(results)

if __name__ == '__main__':
    main()
