name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        # '3.9' is too old for numpy/scipy/...
        # '3.13' is not yet available for torchvision
      fail-fast: false  # Continue with other versions if one fails
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache downloaded files
      uses: actions/cache@v4
      id: cache-files
      with:
        path: ~/.sinatools
        key: sinatools-models-v1

    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel setuptools_rust maturin
    
    - name: Run setup.py develop
      run: |
        python setup.py develop
        pip install pytest
    
    - name: Download files
      if: steps.cache-files.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.sinatools
        download_files wsd synonyms relation
    
    - name: Run pytest
      run: |
        python -m pytest -vv tests/
