name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.8'
    
    - name: Cache downloaded files
      uses: actions/cache@v4
      id: cache-files
      with:
        path: ~/.sinatools
        key: sinatools-models-v1
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run setup.py develop
      run: |
        python setup.py develop
        pip install pytest
    
    - name: Download files
      if: steps.cache-files.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.sinatools
        download_files
    
    - name: Run pytest
      run: |
        python -m pytest -vv tests/
